spring:
  datasource:
    hikari:
      maximum-pool-size: 3
    url: jdbc:${DATABASE_URL}
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        use_nationalized_character_data: true


jwt:
  secret: verySecretPhraseISwear
  header: Authorization
