spring:
  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: verySecretPhraseISwear
  header: Authorization
